e_exome_sequencing/data/variant_calling_files$ gemini load --cores 4 -v reannotated.vcf.gz -t snpEff -p family.ped db.gemini
Traceback (most recent call last):
  File "/home/mp067823/anaconda3/envs/gemini_env/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/home/mp067823/anaconda3/envs/gemini_env/lib/python3.8/site-packages/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/home/mp067823/anaconda3/envs/gemini_env/lib/python3.8/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/home/mp067823/anaconda3/envs/gemini_env/lib/python3.8/site-packages/gemini/gemini_load.py", line 23, in load
    annos = annotations.get_anno_files(args)
  File "/home/mp067823/anaconda3/envs/gemini_env/lib/python3.8/site-packages/gemini/annotations.py", line 22, in get_anno_files
    config = read_gemini_config(args=args)
  File "/home/mp067823/anaconda3/envs/gemini_env/lib/python3.8/site-packages/gemini/config.py", line 53, in read_gemini_config
    fname = _get_config_file(dirs, use_globals=use_globals)
  File "/home/mp067823/anaconda3/envs/gemini_env/lib/python3.8/site-packages/gemini/config.py", line 45, in _get_config_file
    raise ValueError("GEMINI configuration file {0} not found in {1}.\n"
ValueError: GEMINI configuration file gemini-config.yaml not found in ['/home/mp067823/', '/home/mp067823/gemini', '/usr/local/share/gemini', '/home/mp067823/.gemini'].
Please ensure the GEMINI data is installed using the install-data.py script
http://gemini.readthedocs.org/en/latest/content/installation.html
